package Paneles;

import Clases.CrearSilabo;
import Clases.Silabo;
import static Data.Data.docenteLogged;
import prototipo.JFPrincipal;
import javax.swing.JFrame;
import prototipo.JFGenerador;

/**
 *
 * @author junio
 */
public class JPBienvenida extends javax.swing.JPanel {

    private JFGenerador generador;
    private Silabo silabo;

    /**
     * Creates new form JPBienvenida
     */
    public JPBienvenida(JFGenerador generador, Silabo silabo) {
        initComponents();
        this.generador = generador;
        this.silabo = silabo;
      
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnGestionar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        lblCrear = new javax.swing.JLabel();
        lblGestionar = new javax.swing.JLabel();
        lblExportar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("SF UI  Text", 0, 14)); // NOI18N
        jTextPane1.setText("El Generador de Sílabos de la UNPRG es una herramienta digital diseñada para facilitar la elaboración, organización y gestión de los sílabos académicos por parte de los docentes. Esta plataforma permite estructurar de manera clara y ordenada los contenidos, objetivos, metodologías, cronogramas y criterios de evaluación de cada asignatura. Además, proporciona funciones que agilizan el proceso de planificación académica y garantizan la coherencia con los lineamientos institucionales, promoviendo una enseñanza más eficiente y alineada con los estándares educativos de la universidad.");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Bienvenido");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 102, 204));
        lblNombre.setText("\"Docente\"");

        jLabel3.setFont(new java.awt.Font("SF UI  Text Med", 1, 24)); // NOI18N
        jLabel3.setText("Generador Silabos - Universidad Nacional Pedro Ruiz Gallo");

        btnCrear.setBackground(new java.awt.Color(255, 255, 255));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_CrearSilabo.png"))); // NOI18N
        btnCrear.setBorder(null);
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnGestionar.setBackground(new java.awt.Color(255, 255, 255));
        btnGestionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_GestionarSilabo.jpg"))); // NOI18N
        btnGestionar.setBorder(null);
        btnGestionar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActionPerformed(evt);
            }
        });

        btnExportar.setBackground(new java.awt.Color(255, 255, 255));
        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_ExportarSilabo.png"))); // NOI18N
        btnExportar.setBorder(null);
        btnExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        lblCrear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCrear.setForeground(new java.awt.Color(0, 0, 0));
        lblCrear.setText("Crear Silabo");

        lblGestionar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGestionar.setForeground(new java.awt.Color(0, 0, 0));
        lblGestionar.setText("Gestionar Silabo");

        lblExportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblExportar.setForeground(new java.awt.Color(0, 0, 0));
        lblExportar.setText("Exportar Silabo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(111, 111, 111)
                        .addComponent(lblGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110)
                        .addComponent(btnGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnExportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        JFPrincipal frm = new JFPrincipal(generador, silabo);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActionPerformed
        /*JIGestionSilabos frm = JIGestionSilabos.crear(this.dpContenedor);
        frm.setResizable(true);
        frm.setClosable(true);
        frm.setIconifiable(true);
        frm.setVisible(true);

        frm.setVisible(true);
        try {
            frm.setMaximum(true);
        } catch (Exception e) {
        }*/
    }//GEN-LAST:event_btnGestionarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
       CrearSilabo Cr = new CrearSilabo(silabo);
       Cr.Crear();
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnGestionar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblCrear;
    private javax.swing.JLabel lblExportar;
    private javax.swing.JLabel lblGestionar;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables

    

}
