package Paneles;

import Clases.Curso;
import Clases.ListaEscuela;
import Clases.Silabo;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import prototipo.JFGenerador;
import static Data.Data.*;

import prototipo.modelos.table.DesempeñosTableModel;

public class JPInicio extends javax.swing.JPanel {

    private DesempeñosTableModel modelo = new DesempeñosTableModel();

    private JFGenerador padre;

    private Silabo silabo;

    private List<Curso> cursosActuales = new ArrayList<>();

    public JPInicio(JFGenerador padre, Silabo silabo) {

        initComponents();
        this.cargarCursos(silabo.getEscuelaProfesional(), silabo.getCiclo());
        this.padre = padre;
        this.silabo = silabo;

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panInformacionGeneral = new javax.swing.JPanel();
        lblInformacionGeneral = new javax.swing.JLabel();
        lblProgramaEstudio = new javax.swing.JLabel();
        lblEscuelaProfesional = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblModalidad = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        lblCodigoCurso = new javax.swing.JLabel();
        txtProgramaEst = new javax.swing.JTextField();
        txtEscuelaProf = new javax.swing.JTextField();
        txtCodigoCurso = new javax.swing.JTextField();
        cboModalidad = new javax.swing.JComboBox<>();
        lblHorasSemanales = new javax.swing.JLabel();
        lblHoraTeoricas = new javax.swing.JLabel();
        lblHorasPracticas = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        txtHorasTeoricas = new javax.swing.JTextField();
        txtHorasPracticas = new javax.swing.JTextField();
        lblInicioDuracion = new javax.swing.JLabel();
        txtFinalDuracion = new javax.swing.JTextField();
        lblFinalDuracion = new javax.swing.JLabel();
        txtHorasSemanles = new javax.swing.JTextField();
        lblDocente = new javax.swing.JLabel();
        txtDocente = new javax.swing.JTextField();
        spCreditos = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        lblSumilla = new javax.swing.JLabel();
        lblCompetenciasProfesionales = new javax.swing.JLabel();
        lblCapacidadCurso = new javax.swing.JLabel();
        lblDesempeñosUnidades = new javax.swing.JLabel();
        btnSiguente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDesempeño = new javax.swing.JTable();
        spDesempeños = new javax.swing.JSpinner();
        lblNDesempeños = new javax.swing.JLabel();
        cboCurso = new javax.swing.JComboBox<>();
        txtPrerequisito = new javax.swing.JTextField();
        lblPrerequisito = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCompetenciasProfesionales = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtSumilla = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCapacidadCurso = new javax.swing.JTextArea();
        txtCiclo = new javax.swing.JTextField();
        lblCodigoCurso2 = new javax.swing.JLabel();
        txtInicioDuracion = new javax.swing.JTextField();

        panInformacionGeneral.setBackground(new java.awt.Color(255, 255, 255));

        lblInformacionGeneral.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        lblInformacionGeneral.setForeground(new java.awt.Color(0, 153, 255));
        lblInformacionGeneral.setText("•    Información general");

        lblProgramaEstudio.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblProgramaEstudio.setText("Programa de Estudios");

        lblEscuelaProfesional.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblEscuelaProfesional.setText("Escuela Profesional");

        lblCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCurso.setText("Curso");

        lblModalidad.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblModalidad.setText("Modalidad");

        lblDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblDuracion.setText("Duracion ");

        lblCreditos.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCreditos.setText("•  Creditos");

        lblCodigoCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCodigoCurso.setText("Codigo del curso");

        txtProgramaEst.setEditable(false);
        txtProgramaEst.setBackground(new java.awt.Color(204, 204, 204));
        txtProgramaEst.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtProgramaEst.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtEscuelaProf.setEditable(false);
        txtEscuelaProf.setBackground(new java.awt.Color(204, 204, 204));
        txtEscuelaProf.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtEscuelaProf.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtCodigoCurso.setEditable(false);
        txtCodigoCurso.setBackground(new java.awt.Color(204, 204, 204));
        txtCodigoCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtCodigoCurso.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        cboModalidad.setBackground(new java.awt.Color(204, 204, 204));
        cboModalidad.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        cboModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presencial", "Virtual" }));

        lblHorasSemanales.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblHorasSemanales.setText("Horas Semanales:");

        lblHoraTeoricas.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblHoraTeoricas.setText("•  Teoría:");

        lblHorasPracticas.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblHorasPracticas.setText("•  Practica:");

        txtDuracion.setEditable(false);
        txtDuracion.setBackground(new java.awt.Color(204, 204, 204));
        txtDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        txtDuracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDuracion.setText("16 semanas");

        txtHorasTeoricas.setEditable(false);
        txtHorasTeoricas.setBackground(new java.awt.Color(204, 204, 204));
        txtHorasTeoricas.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N

        txtHorasPracticas.setEditable(false);
        txtHorasPracticas.setBackground(new java.awt.Color(204, 204, 204));
        txtHorasPracticas.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N

        lblInicioDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblInicioDuracion.setText("•  Inicio:");

        txtFinalDuracion.setEditable(false);
        txtFinalDuracion.setBackground(new java.awt.Color(204, 204, 204));
        txtFinalDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N

        lblFinalDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblFinalDuracion.setText("•  Final:");

        txtHorasSemanles.setEditable(false);
        txtHorasSemanles.setBackground(new java.awt.Color(204, 204, 204));
        txtHorasSemanles.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtHorasSemanles.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblDocente.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblDocente.setText("Docente");

        txtDocente.setEditable(false);
        txtDocente.setBackground(new java.awt.Color(204, 204, 204));
        txtDocente.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N

        spCreditos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spCreditos.setEnabled(false);
        spCreditos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spCreditosStateChanged(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblSumilla.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblSumilla.setText("Sumilla");

        lblCompetenciasProfesionales.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCompetenciasProfesionales.setText("Competecias Profesionales");

        lblCapacidadCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCapacidadCurso.setText("Capacidad del Curso");

        lblDesempeñosUnidades.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblDesempeñosUnidades.setText("Desempeño de las unidades");

        btnSiguente.setBackground(new java.awt.Color(0, 102, 204));
        btnSiguente.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnSiguente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguente.setText("Siguiente");
        btnSiguente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguenteActionPerformed(evt);
            }
        });

        tblDesempeño.setBackground(new java.awt.Color(204, 204, 204));
        tblDesempeño.setModel(this.modelo);
        jScrollPane1.setViewportView(tblDesempeño);

        spDesempeños.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spDesempeños.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spDesempeñosStateChanged(evt);
            }
        });

        lblNDesempeños.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblNDesempeños.setText("•  N° Desempeños:");

        cboCurso.setBackground(new java.awt.Color(204, 204, 204));
        cboCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        cboCurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCursoItemStateChanged(evt);
            }
        });

        txtPrerequisito.setBackground(new java.awt.Color(204, 204, 204));
        txtPrerequisito.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtPrerequisito.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblPrerequisito.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblPrerequisito.setText("Prerequisito");

        txtCompetenciasProfesionales.setBackground(new java.awt.Color(204, 204, 204));
        txtCompetenciasProfesionales.setColumns(20);
        txtCompetenciasProfesionales.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        txtCompetenciasProfesionales.setRows(5);
        jScrollPane4.setViewportView(txtCompetenciasProfesionales);

        txtSumilla.setBackground(new java.awt.Color(204, 204, 204));
        txtSumilla.setColumns(20);
        txtSumilla.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        txtSumilla.setRows(5);
        txtSumilla.setToolTipText("");
        jScrollPane5.setViewportView(txtSumilla);

        txtCapacidadCurso.setBackground(new java.awt.Color(204, 204, 204));
        txtCapacidadCurso.setColumns(20);
        txtCapacidadCurso.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        txtCapacidadCurso.setRows(5);
        jScrollPane6.setViewportView(txtCapacidadCurso);

        txtCiclo.setEditable(false);
        txtCiclo.setBackground(new java.awt.Color(204, 204, 204));
        txtCiclo.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtCiclo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCodigoCurso2.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblCodigoCurso2.setText("CICLO");

        txtInicioDuracion.setBackground(new java.awt.Color(204, 204, 204));
        txtInicioDuracion.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtInicioDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInicioDuracionKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panInformacionGeneralLayout = new javax.swing.GroupLayout(panInformacionGeneral);
        panInformacionGeneral.setLayout(panInformacionGeneralLayout);
        panInformacionGeneralLayout.setHorizontalGroup(
            panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblInformacionGeneral)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInformacionGeneralLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEscuelaProf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboModalidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEscuelaProfesional)
                                    .addComponent(lblModalidad)
                                    .addComponent(lblProgramaEstudio)
                                    .addComponent(lblCurso)
                                    .addComponent(lblCodigoCurso)
                                    .addComponent(txtProgramaEst)
                                    .addComponent(lblPrerequisito))
                                .addGap(6, 6, 6))
                            .addComponent(cboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrerequisito, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addComponent(lblHoraTeoricas)
                                .addGap(8, 8, 8)
                                .addComponent(txtHorasTeoricas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblHorasPracticas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHorasPracticas)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInformacionGeneralLayout.createSequentialGroup()
                                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(spCreditos))
                                    .addComponent(lblCreditos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                        .addComponent(lblHorasSemanales)
                                        .addGap(0, 0, 0)
                                        .addComponent(txtHorasSemanles, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                                .addGap(137, 137, 137))
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addComponent(lblCodigoCurso2)
                                .addGap(6, 6, 6))
                            .addComponent(txtCiclo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblInicioDuracion)
                                    .addComponent(lblDuracion))
                                .addGap(18, 18, 18)
                                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                        .addComponent(txtDuracion)
                                        .addGap(172, 172, 172))
                                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                        .addComponent(txtInicioDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblFinalDuracion)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFinalDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addComponent(lblDocente)
                                .addGap(447, 447, 447))
                            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSumilla)
                                            .addComponent(lblCompetenciasProfesionales)
                                            .addComponent(lblCapacidadCurso)
                                            .addComponent(lblDesempeñosUnidades))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane6)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane5)
                                    .addComponent(txtDocente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())))
                    .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblNDesempeños)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spDesempeños, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInformacionGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguente)
                .addContainerGap())
        );
        panInformacionGeneralLayout.setVerticalGroup(
            panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInformacionGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacionGeneral)
                .addGap(9, 9, 9)
                .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panInformacionGeneralLayout.createSequentialGroup()
                            .addComponent(lblDocente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSumilla)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCompetenciasProfesionales)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblCapacidadCurso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblDesempeñosUnidades)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(spDesempeños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNDesempeños))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panInformacionGeneralLayout.createSequentialGroup()
                        .addComponent(lblProgramaEstudio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProgramaEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEscuelaProfesional)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEscuelaProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblCodigoCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblPrerequisito)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrerequisito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodigoCurso2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCreditos)
                            .addComponent(spCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHorasSemanales)
                            .addComponent(txtHorasSemanles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHorasTeoricas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraTeoricas)
                            .addComponent(txtHorasPracticas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHorasPracticas))
                        .addGap(18, 18, 18)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuracion)
                            .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblInicioDuracion)
                                .addComponent(txtInicioDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panInformacionGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFinalDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFinalDuracion)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnSiguente)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panInformacionGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panInformacionGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void spCreditosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spCreditosStateChanged
        //calcularHorasDesdeCreditos();
    }//GEN-LAST:event_spCreditosStateChanged

    private void btnSiguenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguenteActionPerformed

        if (validarDatos() == true) {
            this.silabo.setFacultad(txtProgramaEst.getText());
            this.silabo.setEscuelaProfesional(txtEscuelaProf.getText());
            this.silabo.setCurso(cboCurso.getSelectedItem().toString());
            this.silabo.setCodigoCurso(txtCodigoCurso.getText());
            this.silabo.setModalidad(cboModalidad.getSelectedItem().toString());
            this.silabo.setCreditos((int) spCreditos.getValue());
            this.silabo.setHorasSemanales(Integer.parseInt(txtHorasSemanles.getText()));
            this.silabo.setHorasTeoricas(Integer.parseInt(txtHorasTeoricas.getText()));
            this.silabo.setHorasPracticas(Integer.parseInt(txtHorasPracticas.getText()));
            this.silabo.setDuracion(txtDuracion.getText());
            this.silabo.setInicioDuracion(txtInicioDuracion.getText());
            this.silabo.setFinalDuracion(txtFinalDuracion.getText());
            this.silabo.setDocente(txtDocente.getText());
            this.silabo.setSumilla(txtSumilla.getText());
            this.silabo.setCompetenciasProf(txtCompetenciasProfesionales.getText());
            this.silabo.setCapacidadCurso(txtCapacidadCurso.getText());
            this.silabo.setDesempeños(modelo.getDesempeños());

            silabos.add(this.silabo);

            JPGestionUnidades frm = new JPGestionUnidades(this.modelo.getDesempeños(), this.padre, this.silabo);
            this.padre.cambiarPanel(frm);

        }
    }//GEN-LAST:event_btnSiguenteActionPerformed

    private void spDesempeñosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spDesempeñosStateChanged
        int cantidad = (int) spDesempeños.getValue();
        modelo.ajustarCantidadFilas(cantidad);
    }//GEN-LAST:event_spDesempeñosStateChanged

    private void cboCursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCursoItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            String nombreCursoSeleccionado = cboCurso.getSelectedItem().toString();

            for (Curso curso : cursosActuales) {
                if (curso.getNombre().equals(nombreCursoSeleccionado)) {
                    txtCodigoCurso.setText(curso.getCodigo());
                    txtHorasPracticas.setText(curso.gethPracticas());
                    txtHorasTeoricas.setText(curso.gethTeoricas());
                    txtHorasSemanles.setText("" + (Integer.parseInt(curso.gethPracticas()) + Integer.parseInt(curso.gethTeoricas())));
                    spCreditos.setValue(curso.getCreditos());
                    txtPrerequisito.setText(curso.getPrerequisito());
                    txtSumilla.setText(curso.getSumilla());
                    txtSumilla.setLineWrap(true);
                    txtSumilla.setWrapStyleWord(true);
                    txtCompetenciasProfesionales.setText(curso.getCompetencia());
                    txtCompetenciasProfesionales.setLineWrap(true);
                    txtCompetenciasProfesionales.setWrapStyleWord(true);
                    txtCapacidadCurso.setText(curso.getCapacidad());
                    txtCapacidadCurso.setLineWrap(true);
                    txtCapacidadCurso.setWrapStyleWord(true);

                    // Cargar desempeños en la tabla
                    DesempeñosTableModel modeloDesempeños = (DesempeñosTableModel) tblDesempeño.getModel();
                    modeloDesempeños.setDesempeños(curso.getDesempeño());
                    
                    spDesempeños.setValue(curso.getDesempeño().size()); //Poner el spDesempeños segun el numero de desempeños
                    tblDesempeño.getColumnModel().getColumn(0).setPreferredWidth(100);
                    tblDesempeño.getColumnModel().getColumn(0).setMaxWidth(80);
                    tblDesempeño.getColumnModel().getColumn(0).setMinWidth(70);

                    break;
                }
            }
        }
    }//GEN-LAST:event_cboCursoItemStateChanged

    private void jdcFechaInicio1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdcFechaInicio1PropertyChange

    }//GEN-LAST:event_jdcFechaInicio1PropertyChange

    private void txtInicioDuracionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInicioDuracionKeyReleased
        calcularFechaFinal();
    }//GEN-LAST:event_txtInicioDuracionKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguente;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboModalidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCapacidadCurso;
    private javax.swing.JLabel lblCodigoCurso;
    private javax.swing.JLabel lblCodigoCurso2;
    private javax.swing.JLabel lblCompetenciasProfesionales;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDesempeñosUnidades;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblEscuelaProfesional;
    private javax.swing.JLabel lblFinalDuracion;
    private javax.swing.JLabel lblHoraTeoricas;
    private javax.swing.JLabel lblHorasPracticas;
    private javax.swing.JLabel lblHorasSemanales;
    private javax.swing.JLabel lblInformacionGeneral;
    private javax.swing.JLabel lblInicioDuracion;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblNDesempeños;
    private javax.swing.JLabel lblPrerequisito;
    private javax.swing.JLabel lblProgramaEstudio;
    private javax.swing.JLabel lblSumilla;
    private javax.swing.JPanel panInformacionGeneral;
    private javax.swing.JSpinner spCreditos;
    private javax.swing.JSpinner spDesempeños;
    private javax.swing.JTable tblDesempeño;
    private javax.swing.JTextArea txtCapacidadCurso;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextArea txtCompetenciasProfesionales;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtEscuelaProf;
    private javax.swing.JTextField txtFinalDuracion;
    private javax.swing.JTextField txtHorasPracticas;
    private javax.swing.JTextField txtHorasSemanles;
    private javax.swing.JTextField txtHorasTeoricas;
    private javax.swing.JTextField txtInicioDuracion;
    private javax.swing.JTextField txtPrerequisito;
    private javax.swing.JTextField txtProgramaEst;
    private javax.swing.JTextArea txtSumilla;
    // End of variables declaration//GEN-END:variables

    public void calcularFechaFinal() {
        String fechaTexto = txtInicioDuracion.getText().trim();

        if (fechaTexto.length() < 10) {
            txtFinalDuracion.setText("");  // Limpias el campo mientras escribe
            return;
        }

        try {
            LocalDate inicio = java.time.LocalDate.parse(fechaTexto);
            LocalDate fin = inicio.plusWeeks(16);
            txtFinalDuracion.setText(fin.toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Fecha inválida (usa formato: YYYY-MM-DD)");
        }
    }

    public void setDatosSilabo(Silabo silabo) {
        if (silabo != null) {
            txtProgramaEst.setText(silabo.getFacultad());
            txtEscuelaProf.setText(silabo.getEscuelaProfesional());
            txtDocente.setText(silabo.getDocente());
            txtCiclo.setText(convertirARomano(silabo.getCiclo()));

        }
    }

    private boolean validarDatos() {
        String mensaje = "";

        if (cboCurso.getSelectedItem() == null) {
            mensaje += "- Curso\n";
        }
        if (txtCodigoCurso.getText().trim().isEmpty()) {
            mensaje += "- Codigo del curso\n";
        }
        if (txtInicioDuracion.getText().trim().isEmpty()) {
            mensaje += "- Codigo del curso\n";
        }
        if (txtSumilla.getText().trim().isEmpty()) {
            mensaje += "- Sumilla\n";
        }
        if (txtCapacidadCurso.getText().trim().isEmpty()) {
            mensaje += "- Capacidad del curso\n";
        }
        if (txtCompetenciasProfesionales.getText().trim().isEmpty()) {
            mensaje += "- Compentecias profesionales\n";
        }

        if (!mensaje.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete los siguientes campos:\n" + mensaje, "Campos incompletos", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    private void cargarCursos(String escuela, int ciclo) {
        cursosActuales = ListaEscuela.obtenerCursos(escuela, ciclo);

        DefaultComboBoxModel<String> modeloCurso = new DefaultComboBoxModel<>();
        for (Curso curso : cursosActuales) {
            modeloCurso.addElement(curso.getNombre());
        }

        cboCurso.setModel(modeloCurso);
        cboCurso.setSelectedIndex(-1);

    }

    private String convertirARomano(int numero) {
        String[] romanos = {"I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"};
        if (numero >= 1 && numero <= 10) {
            return romanos[numero - 1];
        }
        return String.valueOf(numero); // por si se sale del rango
    }
}
