package Paneles;

import Clases.Desempeño;
import Clases.Silabo;
import Clases.Unidad;
import ClasesSoporte.Evidencia;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import prototipo.JDSistemaEvaluacion;
import prototipo.JFGenerador;
import prototipo.modelos.table.EvaluacionTableModel;
import static Data.Data.*;

public class JPSistemaEvaluacion extends javax.swing.JPanel {

    private EvaluacionTableModel modeloEvalu;
    private List<Desempeño> desempeños;
    private JFGenerador padre;
     private Silabo silabo;

    public JPSistemaEvaluacion(List<Desempeño> desempeño, JFGenerador padre, Silabo silabo) {
        this.desempeños = desempeño;
        this.silabo = silabo;
        this.padre = padre;
        
        
        modeloEvalu = new EvaluacionTableModel(this.desempeños);
        
        
        initComponents();
        
        
        
//        this.modeloEvalu.setDatos(convertirADatosEvaluacion(desempeños));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSistemaEvaluacion = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSiguente = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setText("• Sistema de evaluación");

        tblSistemaEvaluacion.setBackground(new java.awt.Color(204, 204, 204));
        tblSistemaEvaluacion.setModel(this.modeloEvalu);
        jScrollPane1.setViewportView(tblSistemaEvaluacion);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 204));

        btnAgregar.setBackground(new java.awt.Color(0, 153, 255));
        btnAgregar.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 153, 255));
        btnModificar.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnSiguente.setBackground(new java.awt.Color(0, 102, 204));
        btnSiguente.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnSiguente.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguente.setText("Siguiente");
        btnSiguente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSiguente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguente)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(59, 59, 59)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int pos = this.tblSistemaEvaluacion.getSelectedRow();

        if (pos > -1) {
            String descripcionDesempeño = modeloEvalu.getDesempeño(pos).getDescripcion();

            // Buscar evidencias de la unidad que tenga ese desempeño
            List<Evidencia> evidenciasDelDesempeño = new ArrayList<>();
            for (Unidad unidad : unidades) {
                if (unidad.getDesempeño().equals(descripcionDesempeño)) {
                    evidenciasDelDesempeño = unidad.getEvidencias();
                    break;
                }
            }

            // Pasar las evidencias al JDialog
            JDSistemaEvaluacion frm = new JDSistemaEvaluacion(null, true, evidenciasDelDesempeño);
            frm.setDesempeño(descripcionDesempeño);
            frm.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una unidad");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSiguenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguenteActionPerformed
        // Crea el panel de calificación con el modelo
        JPSistemaCalificacion panelCalificacion = new JPSistemaCalificacion(desempeños, padre, this.silabo);

        // Cambia de panel
        this.padre.cambiarPanel(panelCalificacion);
    }//GEN-LAST:event_btnSiguenteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int pos = this.tblSistemaEvaluacion.getSelectedRow();

        if (pos > -1) {
            String descripcionDesempeño = modeloEvalu.getDesempeño(pos).getDescripcion();

            // Buscar evidencias que ya tienen instrumentos asociados (en la unidad correspondiente)
            List<Evidencia> evidenciasDelDesempeño = new ArrayList<>();
            for (Unidad unidad : unidades) {
                if (unidad.getDesempeño().equals(descripcionDesempeño)) {
                    evidenciasDelDesempeño = unidad.getEvidencias();  // traer todas las evidencias (con instrumentos ya asignados)
                    break;
                }
            }

            if (evidenciasDelDesempeño.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay evidencias para este desempeño aún.");
                return;
            }

            // Abrir el formulario para editar evidencias e instrumentos
            JDSistemaEvaluacion frm = new JDSistemaEvaluacion(null, true, evidenciasDelDesempeño);
            frm.setDesempeño(descripcionDesempeño);
            frm.setVisible(true);

            // Al cerrar el JDialog, si se aceptó, actualizar las evidencias en la unidad correspondiente
            if (frm.wasAccepted()) {
                List<Evidencia> evidenciasActualizadas = frm.getEvidenciasActualizadas();

                // Volver a guardar las evidencias en la unidad correspondiente
                for (Unidad unidad : unidades) {
                    if (unidad.getDesempeño().equals(descripcionDesempeño)) {
                        unidad.setEvidencias(evidenciasActualizadas);
                        break;
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un desempeño.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSiguente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSistemaEvaluacion;
    // End of variables declaration//GEN-END:variables

}
