/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package prototipo;

import Clases.Facultades;
import Data.PlanesEstudioRepository;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import prototipo.modelos.table.FacultadBuscarTableModel;

/**
 *
 * @author junio
 */
public class JDFacultades extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDFacultades.class.getName());

    private String seleccionado;
    private List<String> facultades = new ArrayList<>(PlanesEstudioRepository.obtenerFacultades());
    private List<String> encontrados = new ArrayList<>();
    private int cantidadEncontrados;

    int xMouse, yMouse;

    private FacultadBuscarTableModel modelo = new FacultadBuscarTableModel();

    public JDFacultades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        encontrados.addAll(facultades);
        this.presentarFacultades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFacultad = new javax.swing.JTable();
        lblFacultad = new javax.swing.JLabel();
        txtFacultad = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSeleccionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblIconClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        tblFacultad.setBackground(new java.awt.Color(255, 255, 255));
        tblFacultad.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        tblFacultad.setModel(this.modelo);
        jScrollPane1.setViewportView(tblFacultad);

        lblFacultad.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        lblFacultad.setForeground(new java.awt.Color(0, 0, 0));
        lblFacultad.setText("Facultad");

        txtFacultad.setBackground(new java.awt.Color(255, 255, 255));
        txtFacultad.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        txtFacultad.setForeground(new java.awt.Color(0, 0, 0));
        txtFacultad.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSeleccionar.setBackground(new java.awt.Color(0, 102, 204));
        btnSeleccionar.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 204));
        btnCancelar.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblIconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Close.png"))); // NOI18N
        lblIconClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconClose.setFocusable(false);
        lblIconClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconCloseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblIconCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccionar)
                .addGap(21, 21, 21)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblIconClose))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscar)))
                    .addComponent(lblIconClose))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        this.filtrarFacultades(this.txtFacultad.getText());
        this.presentarFacultades();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        int pos = this.tblFacultad.getSelectedRow();

        if (pos > -1) {
            this.seleccionado = this.encontrados.get(pos);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una facultad");
            this.tblFacultad.requestFocusInWindow();
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.seleccionado = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void lblIconCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblIconCloseMouseClicked

    private void lblIconCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMousePressed

    }//GEN-LAST:event_lblIconCloseMousePressed

    private void lblIconCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconCloseMouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDFacultades dialog = new JDFacultades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblIconClose;
    private javax.swing.JTable tblFacultad;
    private javax.swing.JTextField txtFacultad;
    // End of variables declaration//GEN-END:variables

    public String buscar() {
        this.setVisible(true);
        
        return this.seleccionado;
    }

    private void filtrarFacultades(String criterio) {
        this.encontrados = new ArrayList<>();
        this.cantidadEncontrados = 0;
        
        if(criterio.isBlank() || criterio.isEmpty()){
            encontrados = (List<String>) PlanesEstudioRepository.obtenerFacultades();
        }else{
            for (String nombreFacultad : (List<String>) PlanesEstudioRepository.obtenerFacultades()) {
                if (criterio.length() > 0) {
                    if (criterio.length() <= nombreFacultad.length()) {
                        if (criterio.equalsIgnoreCase(nombreFacultad.substring(0, criterio.length()))) {
                            this.encontrados.add(nombreFacultad);
                            this.cantidadEncontrados++;
                        }
                    }
                } else {
                    this.encontrados.add(nombreFacultad);
                    this.cantidadEncontrados++;
                }
            }
        }
        
    }

    private void presentarFacultades() {
        this.modelo.setFacultades(this.encontrados);
    }

}
