package prototipo;

import ClasesSoporte.Evidencia;
import java.util.List;
import javax.swing.*;
import prototipo.modelos.table.EvidenciasTableModel;

public class JDSistemaEvaluacion extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDSistemaEvaluacion.class.getName());

    private EvidenciasTableModel Evidencias;
    private boolean aceptado = false;

    public JDSistemaEvaluacion(java.awt.Frame parent, boolean modal, List<Evidencia> evidencias) {
        super(parent, modal);
        Evidencias = new EvidenciasTableModel(evidencias);
        initComponents();
        tblEvidencias.setModel(Evidencias);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtAyuda = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lblInstrumentoEvaluación = new javax.swing.JLabel();
        lblEvidencias = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvidencias = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInstrumento = new javax.swing.JTextArea();
        txtDesempeño = new javax.swing.JTextField();
        btnAceptarInstrumento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        txtAyuda.setColumns(20);
        txtAyuda.setRows(5);
        jScrollPane2.setViewportView(txtAyuda);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusCycleRoot(true);

        lblInstrumentoEvaluación.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        lblInstrumentoEvaluación.setForeground(new java.awt.Color(0, 0, 0));
        lblInstrumentoEvaluación.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInstrumentoEvaluación.setText("Instrumentos de Evaluación");

        lblEvidencias.setFont(new java.awt.Font("SF UI  Text Med", 0, 14)); // NOI18N
        lblEvidencias.setForeground(new java.awt.Color(0, 0, 0));
        lblEvidencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEvidencias.setText("   Evidencias del Desempeño");

        tblEvidencias.setBackground(new java.awt.Color(204, 204, 204));
        tblEvidencias.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        tblEvidencias.setForeground(new java.awt.Color(0, 0, 0));
        tblEvidencias.setModel(this.Evidencias);
        jScrollPane1.setViewportView(tblEvidencias);

        btnAgregar.setBackground(new java.awt.Color(0, 102, 204));
        btnAgregar.setFont(new java.awt.Font("SF UI  Text Med", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 102, 204));
        btnModificar.setFont(new java.awt.Font("SF UI  Text Med", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptar.setFont(new java.awt.Font("SF UI  Text Med", 1, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 102, 204));
        btnCancelar.setFont(new java.awt.Font("SF UI  Text Med", 1, 12)); // NOI18N
        btnCancelar.setText(" Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtInstrumento.setBackground(new java.awt.Color(204, 204, 204));
        txtInstrumento.setColumns(20);
        txtInstrumento.setFont(new java.awt.Font("SF UI  Text Med", 0, 12)); // NOI18N
        txtInstrumento.setForeground(new java.awt.Color(0, 0, 0));
        txtInstrumento.setRows(5);
        txtInstrumento.setEnabled(false);
        jScrollPane3.setViewportView(txtInstrumento);

        txtDesempeño.setEditable(false);
        txtDesempeño.setBackground(new java.awt.Color(204, 204, 204));
        txtDesempeño.setForeground(new java.awt.Color(0, 0, 0));

        btnAceptarInstrumento.setBackground(new java.awt.Color(0, 102, 204));
        btnAceptarInstrumento.setFont(new java.awt.Font("SF UI  Text Med", 1, 12)); // NOI18N
        btnAceptarInstrumento.setText("Aceptar");
        btnAceptarInstrumento.setEnabled(false);
        btnAceptarInstrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarInstrumentoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Desempeño:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                    .addComponent(lblInstrumentoEvaluación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModificar)
                                    .addComponent(btnAceptarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(lblEvidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEvidencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesempeño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInstrumentoEvaluación)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptarInstrumento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int pos = tblEvidencias.getSelectedRow();
        if (pos > -1) {
            tblEvidencias.setRowSelectionInterval(pos, pos);
            txtInstrumento.setEnabled(true);
            txtInstrumento.setText("");
            txtInstrumento.requestFocus();
            btnAceptarInstrumento.setEnabled(true);
            btnAgregar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una evidencia de la tabla primero.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAceptarInstrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarInstrumentoActionPerformed
        int pos = tblEvidencias.getSelectedRow();
        if (pos > -1) {
            String instrumento = txtInstrumento.getText().trim();
            if (!instrumento.isEmpty()) {
                EvidenciasTableModel modelo = (EvidenciasTableModel) tblEvidencias.getModel();
                modelo.actualizarInstrumento(pos, instrumento);

                txtInstrumento.setText("");
                txtInstrumento.setEnabled(false);
                btnAceptarInstrumento.setEnabled(false);
                btnModificar.setEnabled(true);  // reactivar
                btnAgregar.setEnabled(true);    // reactivar también
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un instrumento antes de guardar.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una evidencia para asignar instrumento.");
        }
    }//GEN-LAST:event_btnAceptarInstrumentoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        this.aceptado = true;
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int pos = tblEvidencias.getSelectedRow();
        if (pos > -1) {
            Evidencia evidencia = Evidencias.getEvidenciaAt(pos);
            String instrumentoActual = evidencia.getInstrumento();

            txtInstrumento.setEnabled(true);
            txtInstrumento.setText(instrumentoActual != null ? instrumentoActual : "");
            txtInstrumento.requestFocus();

            btnAceptarInstrumento.setEnabled(true);
            btnModificar.setEnabled(false);  // desactivar mientras se edita
            btnAgregar.setEnabled(false);    // evitar conflictos
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una evidencia primero.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                JDSistemaEvaluacion dialog = new JDSistemaEvaluacion(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarInstrumento;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEvidencias;
    private javax.swing.JLabel lblInstrumentoEvaluación;
    private javax.swing.JTable tblEvidencias;
    private javax.swing.JTextArea txtAyuda;
    private javax.swing.JTextField txtDesempeño;
    private javax.swing.JTextArea txtInstrumento;
    // End of variables declaration//GEN-END:variables

    public void setDesempeño(String desempeño) {
        txtDesempeño.setText(desempeño);
    }

    public void cargarEvidenciasParaDesempeño(List<Evidencia> evidencias) {
        Evidencias.setEvidencias(evidencias); // Este método deberías tenerlo en tu TableModel
        tblEvidencias.setModel(Evidencias);    // Se asegura de que el JTable tenga el modelo actualizado
        Evidencias.fireTableDataChanged();    // Notifica al JTable que se actualizó la tabla
    }

    public boolean wasAccepted() {
        return aceptado;
    }

    public List<Evidencia> getEvidenciasActualizadas() {
        return Evidencias.getEvidencias();
    }
}
