package prototipo;

import Clases.Silabo;
import Paneles.JPBienvenida;
import Paneles.JPGestionUnidades;
import Paneles.JPInicio;
import Paneles.JPPerfil;
import java.awt.BorderLayout;
import java.awt.Color;
import static Data.Data.*;

public class JFGenerador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFGenerador.class.getName());

    private JPBienvenida panelBienvenida;
    private JPInicio frm;
    private final Color COLOR_SELECCIONADO = new Color(102, 153, 255); // azul más claro
    private final Color COLOR_NO_SELECCIONADO = new Color(0, 102, 204); // azul por defecto

    private JPGestionUnidades frn;
    JFPrincipal principal;
    private Silabo silabo;

    private boolean bandera = false;

    public JFGenerador() {
        this(new Silabo());
        if (this.panelBienvenida == null) {
            this.panelBienvenida = new JPBienvenida(this, silabo);
        }
        cambiarPanel(this.panelBienvenida);
    }

    public JFGenerador(Silabo silabo) {
        initComponents();
        this.silabo = silabo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panLateral = new javax.swing.JPanel();
        btnGenerador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        panPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panLateral.setBackground(new java.awt.Color(0, 102, 204));

        btnGenerador.setBackground(new java.awt.Color(0, 102, 204));
        btnGenerador.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnGenerador.setForeground(new java.awt.Color(0, 0, 0));
        btnGenerador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Facultad.png"))); // NOI18N
        btnGenerador.setText("GENERADOR");
        btnGenerador.setBorder(null);
        btnGenerador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGenerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneradorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escudo_act_ofic.png"))); // NOI18N

        btnPerfil.setBackground(new java.awt.Color(0, 102, 204));
        btnPerfil.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(0, 0, 0));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_User.png"))); // NOI18N
        btnPerfil.setBorder(null);
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnInicio.setBackground(new java.awt.Color(0, 102, 204));
        btnInicio.setFont(new java.awt.Font("SF UI  Text Med", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 0, 0));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Home.png"))); // NOI18N
        btnInicio.setText("  INICIO");
        btnInicio.setBorder(null);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panLateralLayout = new javax.swing.GroupLayout(panLateral);
        panLateral.setLayout(panLateralLayout);
        panLateralLayout.setHorizontalGroup(
            panLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panLateralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btnPerfil)
        );
        panLateralLayout.setVerticalGroup(
            panLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panLateralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGenerador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnPerfil))
        );

        panPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(panLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(780, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneradorActionPerformed
        if (!bandera) {
            if (this.principal == null || !this.principal.isDisplayable()) {
                this.principal = new JFPrincipal(this, this.silabo);
            }
            this.principal.setVisible(true);
            this.principal.setLocationRelativeTo(null);

        } else {
            this.mostrarPanelInicio();
        }
    }//GEN-LAST:event_btnGeneradorActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        JPPerfil panelPerfil = new JPPerfil(docenteLogged);
        cambiarPanel(panelPerfil);

        btnInicio.setBackground(COLOR_NO_SELECCIONADO);
        btnGenerador.setBackground(COLOR_NO_SELECCIONADO);
        btnPerfil.setBackground(COLOR_SELECCIONADO);

    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        if (this.panelBienvenida == null) {
            this.panelBienvenida = new JPBienvenida(this, this.silabo);
        }

        btnInicio.setBackground(COLOR_SELECCIONADO);
        btnGenerador.setBackground(COLOR_NO_SELECCIONADO);
        btnPerfil.setBackground(COLOR_NO_SELECCIONADO);
        cambiarPanel(this.panelBienvenida);    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFGenerador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnGenerador;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panLateral;
    private javax.swing.JPanel panPrincipal;
    // End of variables declaration//GEN-END:variables

    public void cambiarPanel(javax.swing.JPanel nuevoPanel) {
        panPrincipal.removeAll();
        panPrincipal.setLayout(new BorderLayout());
        panPrincipal.add(nuevoPanel, BorderLayout.CENTER);
        panPrincipal.revalidate();
        panPrincipal.repaint();
    }

    public void mostrarPanelInicio() {
        if (this.frm == null) {
            this.frm = new JPInicio(this, this.silabo);
        }
        this.frm.setDatosSilabo(this.silabo);

        btnInicio.setBackground(COLOR_NO_SELECCIONADO);
        btnGenerador.setBackground(COLOR_SELECCIONADO);
        btnPerfil.setBackground(COLOR_NO_SELECCIONADO);

        cambiarPanel(this.frm);
    }

    public void setBanderaLlenadoCompleto(boolean completado) {
        this.bandera = completado;
    }

}
