/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Gestion;

import Clases.Docente;
import java.awt.Color;
import alerts.MostrarMensaje;

/**
 *
 * @author USUARIO
 */
public class JDCambiarContraseña extends javax.swing.JDialog {

    private static Docente docCambio;

    /**
     * Creates new form JDCambiarContraseña
     */
    public JDCambiarContraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.paneCambiarContraseña.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneCambiarContraseña = new javax.swing.JPanel();
        lblSaludo = new javax.swing.JLabel();
        lblNuevaContraseña = new javax.swing.JLabel();
        lblIconContraseña = new javax.swing.JLabel();
        lblConfirmContraseña = new javax.swing.JLabel();
        lblIconContraseñaConfirm = new javax.swing.JLabel();
        pwdContraseñaNueva = new javax.swing.JPasswordField();
        pwdConfirmarContraseña = new javax.swing.JPasswordField();
        btnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        paneCambiarContraseña.setBackground(new java.awt.Color(255, 255, 255));

        lblSaludo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSaludo.setText("¡Hola, Renato!");

        lblNuevaContraseña.setText("Ingrese nueva contraseña:");

        lblIconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Contraseña.png"))); // NOI18N

        lblConfirmContraseña.setText("Confirme su contraseña:");

        lblIconContraseñaConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Contraseña.png"))); // NOI18N

        pwdContraseñaNueva.setForeground(Color.GRAY);
        pwdContraseñaNueva.setText("12345678");
        pwdContraseñaNueva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pwdContraseñaNueva.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdContraseñaNuevaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdContraseñaNuevaFocusLost(evt);
            }
        });

        pwdConfirmarContraseña.setForeground(Color.GRAY);
        pwdConfirmarContraseña.setText("12345678");
        pwdConfirmarContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pwdConfirmarContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdConfirmarContraseñaFocusGained(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 204));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneCambiarContraseñaLayout = new javax.swing.GroupLayout(paneCambiarContraseña);
        paneCambiarContraseña.setLayout(paneCambiarContraseñaLayout);
        paneCambiarContraseñaLayout.setHorizontalGroup(
            paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCambiarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneCambiarContraseñaLayout.createSequentialGroup()
                        .addComponent(lblIconContraseñaConfirm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdConfirmarContraseña))
                    .addGroup(paneCambiarContraseñaLayout.createSequentialGroup()
                        .addComponent(lblIconContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pwdContraseñaNueva))
                    .addGroup(paneCambiarContraseñaLayout.createSequentialGroup()
                        .addGroup(paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConfirmContraseña)
                            .addComponent(lblNuevaContraseña))
                        .addGap(0, 198, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCambiarContraseñaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)))
                .addContainerGap())
        );
        paneCambiarContraseñaLayout.setVerticalGroup(
            paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneCambiarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaludo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNuevaContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdContraseñaNueva))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneCambiarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconContraseñaConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdConfirmarContraseña))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCambiarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCambiarContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if (ValidarDatos()) {
            docCambio.setContraseña(String.valueOf(this.pwdContraseñaNueva.getPassword()));
            MostrarMensaje.confirm("Contraseña modificada.");
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void pwdContraseñaNuevaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaNuevaFocusGained
        if(String.valueOf(this.pwdContraseñaNueva.getPassword()).equals("12345678")){
            this.pwdContraseñaNueva.setText("");
            this.pwdContraseñaNueva.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_pwdContraseñaNuevaFocusGained

    private void pwdConfirmarContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmarContraseñaFocusGained
        if(String.valueOf(this.pwdConfirmarContraseña.getPassword()).equals("12345678")){
            this.pwdConfirmarContraseña.setText("");
            this.pwdConfirmarContraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwdConfirmarContraseñaFocusGained

    private void pwdContraseñaNuevaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaNuevaFocusLost

    }//GEN-LAST:event_pwdContraseñaNuevaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDCambiarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDCambiarContraseña dialog = new JDCambiarContraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblConfirmContraseña;
    private javax.swing.JLabel lblIconContraseña;
    private javax.swing.JLabel lblIconContraseñaConfirm;
    private javax.swing.JLabel lblNuevaContraseña;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JPanel paneCambiarContraseña;
    private javax.swing.JPasswordField pwdConfirmarContraseña;
    private javax.swing.JPasswordField pwdContraseñaNueva;
    // End of variables declaration//GEN-END:variables

    void cambiarContraseña(Docente docenteRecuperando) {
        this.lblSaludo.setText("¡Hola, " + docenteRecuperando.getUserName() + "!");
        docCambio = docenteRecuperando;
        this.setVisible(true);
    }

    private boolean ValidarDatos() {
        String errorMessage = "";
        String regex = "^(?=.*[A-Za-z])(?=.*\\d).{8,}$";

        if (String.valueOf(this.pwdContraseñaNueva.getPassword()).isBlank() || String.valueOf(this.pwdContraseñaNueva.getPassword()).isEmpty() || !String.valueOf(this.pwdContraseñaNueva.getPassword()).matches(regex)) {
            errorMessage += "Se necesita una contraseña válida.\n- 8 caracteres como mínimo.\n- Al menos un número.\n- Al menos una letra.";
        }else if(errorMessage.isEmpty() && !String.valueOf(this.pwdContraseñaNueva.getPassword()).equals(String.valueOf(this.pwdConfirmarContraseña.getPassword()))) {
            errorMessage += "Las contraseñas no coinciden.";
        }
        
        if(!errorMessage.isEmpty()){
            MostrarMensaje.error(errorMessage);
            return false;
        }else{
            return true;
        }
    }
}
