/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Gestion;
import Clases.Docente;
import alerts.MostrarMensaje;
import java.awt.Color;
import prototipo.Prototipo;
import static Data.Data.*;

/**
 *
 * @author USUARIO
 */
public class JDOlvidoContraseña extends javax.swing.JDialog {

    /**
     * Creates new form JDOlvidoContraseña
     */
    public JDOlvidoContraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.paneOlvidoContraseña.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneOlvidoContraseña = new javax.swing.JPanel();
        lblTitleOlvidoContraseña = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblIconCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        paneOlvidoContraseña.setBackground(new java.awt.Color(255, 255, 255));

        lblTitleOlvidoContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitleOlvidoContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleOlvidoContraseña.setText("RESTABLECER CONTRASEÑA");

        lblCorreo.setText("Ingrese su correo institucional:");

        lblIconCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Email.png"))); // NOI18N

        txtCorreo.setForeground(Color.GRAY);
        txtCorreo.setText("example@unprg.edu.pe");
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 204));
        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneOlvidoContraseñaLayout = new javax.swing.GroupLayout(paneOlvidoContraseña);
        paneOlvidoContraseña.setLayout(paneOlvidoContraseñaLayout);
        paneOlvidoContraseñaLayout.setHorizontalGroup(
            paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleOlvidoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                        .addComponent(lblCorreo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                        .addComponent(lblIconCorreo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOlvidoContraseñaLayout.createSequentialGroup()
                        .addGap(0, 181, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirmar)))
                .addContainerGap())
        );
        paneOlvidoContraseñaLayout.setVerticalGroup(
            paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleOlvidoContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneOlvidoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneOlvidoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if(this.txtCorreo.getText().equals("example@unprg.edu.pe")){
            this.txtCorreo.setText("");
            this.txtCorreo.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_txtCorreoFocusGained

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        boolean banDoc = false;
        
        if(ValidarDatos()){
            for(Docente doc : docentes){
                if(doc.getCorreo().equals(this.txtCorreo.getText())){
                    JDPreguntaSeguridad frmPreguntaSeguridad = new JDPreguntaSeguridad(null, true);
                    frmPreguntaSeguridad.setEnunciadoPregunta(this.txtCorreo.getText());
                    frmPreguntaSeguridad.setLocationRelativeTo(this);
                    this.setVisible(false);
                    frmPreguntaSeguridad.setVisible(true);
                    
                    banDoc = true;
                    break;
                }
            }
            
            if(!banDoc){
                MostrarMensaje.alert("Usuario no registrado");
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDOlvidoContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDOlvidoContraseña dialog = new JDOlvidoContraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblIconCorreo;
    private javax.swing.JLabel lblTitleOlvidoContraseña;
    private javax.swing.JPanel paneOlvidoContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables

    private boolean ValidarDatos() {
        String errorMessage = "";
        
        if(this.txtCorreo.getText().isBlank() || this.txtCorreo.getText().isEmpty() || this.txtCorreo.getText().equals("example@unprg.edu.pe")){
            errorMessage += "Ingrese su correo institucional";
        }else if(!this.txtCorreo.getText().matches("^[a-z._]+@unprg\\.edu\\.pe$")){
            errorMessage += "Correo no pertenece a la UNPRG";
        }
        
        if(errorMessage.isEmpty()){
            return true;
        }else {
            MostrarMensaje.error(errorMessage);
            return false;
        }
    }
}
