/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Gestion;

import Clases.Docente;
import alerts.MostrarMensaje;
import java.awt.Color;
import prototipo.Prototipo;
import static Data.Data.*;

/**
 *
 * @author USUARIO
 */
public class JDPreguntaSeguridad extends javax.swing.JDialog {
    private String respuestaValida;
    private int numIntentos = 0;
    public Docente docenteRecuperando;
    /**
     * Creates new form JDOlvidoContraseña
     */
    
    public JDPreguntaSeguridad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.paneOlvidoContraseña.requestFocusInWindow();
        this.lblRespuestaIncorrecta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneOlvidoContraseña = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblEnunciadoPregunta = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();
        lblRespuestaIncorrecta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneOlvidoContraseña.setBackground(new java.awt.Color(255, 255, 255));
        paneOlvidoContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255), 5));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImagePreguntaSeguridad.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("PREGUNTA DE SEGURIDAD");

        lblEnunciadoPregunta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEnunciadoPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnunciadoPregunta.setText("Pregunta precargada");

        txtRespuesta.setBackground(new java.awt.Color(204, 255, 255));
        txtRespuesta.setForeground(Color.LIGHT_GRAY);
        txtRespuesta.setText("Ingrese su respuesta");
        txtRespuesta.setBorder(null);
        txtRespuesta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRespuestaFocusGained(evt);
            }
        });
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });

        btnValidar.setBackground(new java.awt.Color(83, 16, 198));
        btnValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("VALIDAR");
        btnValidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        lblRespuestaIncorrecta.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblRespuestaIncorrecta.setForeground(new java.awt.Color(255, 0, 0));
        lblRespuestaIncorrecta.setText("Respuesta incorrecta (Intentos restantes: )");

        javax.swing.GroupLayout paneOlvidoContraseñaLayout = new javax.swing.GroupLayout(paneOlvidoContraseña);
        paneOlvidoContraseña.setLayout(paneOlvidoContraseñaLayout);
        paneOlvidoContraseñaLayout.setHorizontalGroup(
            paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnunciadoPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addComponent(txtRespuesta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneOlvidoContraseñaLayout.createSequentialGroup()
                        .addComponent(lblRespuestaIncorrecta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValidar)))
                .addContainerGap())
        );
        paneOlvidoContraseñaLayout.setVerticalGroup(
            paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEnunciadoPregunta)
                        .addGap(12, 12, 12)
                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(paneOlvidoContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnValidar))
                            .addGroup(paneOlvidoContraseñaLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblRespuestaIncorrecta)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(paneOlvidoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 560, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if(validarDatos()){
            if(respuestaValida.equalsIgnoreCase(this.txtRespuesta.getText())){
                JDCambiarContraseña frmCambiarContraseña = new JDCambiarContraseña(null, true);
                frmCambiarContraseña.setLocationRelativeTo(this);
                this.setVisible(false);
                frmCambiarContraseña.cambiarContraseña(docenteRecuperando);
            }else{
                numIntentos++;
                if(numIntentos == 3){
                    this.dispose();
                    MostrarMensaje.alert("Ha superado el número de intentos.\nVuelva a iniciar el programa e intente de nuevo");
                    System.exit(0);
                }else{
                    this.lblRespuestaIncorrecta.setText("Respuesta incorrecta (Intentos restantes: "+ (3-numIntentos) + ")");
                    this.lblRespuestaIncorrecta.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void txtRespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRespuestaFocusGained
        this.txtRespuesta.setForeground(Color.black);
        this.txtRespuesta.setText("");
    }//GEN-LAST:event_txtRespuestaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDPreguntaSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDPreguntaSeguridad dialog = new JDPreguntaSeguridad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnunciadoPregunta;
    private javax.swing.JLabel lblRespuestaIncorrecta;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel paneOlvidoContraseña;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables

    void setEnunciadoPregunta(String intentoCorreo) {
        for(Docente doc : docentes){
            if(doc.getCorreo().equals(intentoCorreo)){
                docenteRecuperando = doc;
                this.lblEnunciadoPregunta.setText(PREGUNTAS_SEGURIDAD[doc.getIndexPreguntaSeguridad()]);
                respuestaValida = doc.getRespuestaSeguridad();
                break;
            }
        }
    }

    private boolean validarDatos() {
        if(this.txtRespuesta.getText().isBlank() || this.txtRespuesta.getText().isEmpty() || this.txtRespuesta.getText().equals("Ingrese su respuesta")){
            this.lblRespuestaIncorrecta.setText("Respuesta requerida.");
            lblRespuestaIncorrecta.setVisible(true);
            
            this.txtRespuesta.setForeground(Color.LIGHT_GRAY);
            this.txtRespuesta.setText("Ingrese su respuesta");
            
            return false;
        }else{
            return true;
        }
    }
}
