/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gestion;

import Clases.Docente;
import enums.EnumPaths;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.Point;
import prototipo.Prototipo;
import static Data.Data.*;

/**
 *
 * @author USUARIO
 */
public class JFInicioSesion extends javax.swing.JFrame {
    int xMouse, yMouse;
    private static JFInicioSesion frmLogin = null;
    private static String errorCorreo = "", errorContraseña = "";
    
    private static String intentoCorreo = "";
    private static int contadorIntentos = 0;
    
    public static JFrame crear() {
        if(frmLogin == null){
            frmLogin = new JFInicioSesion();
        }
        
        return frmLogin;
    }

    /**
     * Creates new form JFLogin
     */
    public JFInicioSesion() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource(EnumPaths.ICON.getRuta())).getImage());
        this.paneLogin.requestFocusInWindow();
        ocultarErrorMessages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblIconClose = new javax.swing.JLabel();
        paneLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        pwdContraseña = new javax.swing.JPasswordField();
        lblRecuperarContraseña = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblIconEmail = new javax.swing.JLabel();
        lblIconContraseña = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        lblErrorCorreo = new javax.swing.JLabel();
        lblErrorContraseña = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PlazaDelSaber_UNRPG.png"))); // NOI18N
        jLabel1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        paneHeader.setBackground(new java.awt.Color(255, 255, 255));
        paneHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneHeaderMouseDragged(evt);
            }
        });
        paneHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneHeaderMousePressed(evt);
            }
        });

        lblIconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Close.png"))); // NOI18N
        lblIconClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIconClose.setFocusable(false);
        lblIconClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconCloseMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblIconCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblIconCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(0, 828, Short.MAX_VALUE)
                .addComponent(lblIconClose))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addComponent(lblIconClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(paneHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        paneLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagotipo.png"))); // NOI18N
        jLabel2.setFocusable(false);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmail.setText("CORREO INSTITUCIONAL:");

        txtEmail.setForeground(Color.LIGHT_GRAY);
        txtEmail.setText("example@unprg.edu.pe");
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtEmailMousePressed(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseña.setText("CONTRASEÑA:");

        pwdContraseña.setForeground(Color.LIGHT_GRAY);
        pwdContraseña.setText("12345678");
        pwdContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pwdContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdContraseñaFocusLost(evt);
            }
        });
        pwdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseñaActionPerformed(evt);
            }
        });

        lblRecuperarContraseña.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblRecuperarContraseña.setForeground(new java.awt.Color(83, 16, 198));
        lblRecuperarContraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperarContraseña.setText("¿Olvidó su contraseña?");
        lblRecuperarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRecuperarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecuperarContraseñaMouseClicked(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(0, 102, 204));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("ACCEDER");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblIconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Email.png"))); // NOI18N
        lblIconEmail.setFocusable(false);

        lblIconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Contraseña.png"))); // NOI18N
        lblIconContraseña.setFocusable(false);

        btnRegistrar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setText("NUEVO USUARIO");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 204), 1, true));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorCorreo.setText("MessageError");

        lblErrorContraseña.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorContraseña.setText("MessageError");

        lblIntentos.setForeground(new java.awt.Color(255, 0, 0));
        lblIntentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIntentos.setText("Intentos restantes:");
        lblIntentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paneLoginLayout = new javax.swing.GroupLayout(paneLogin);
        paneLogin.setLayout(paneLoginLayout);
        paneLoginLayout.setHorizontalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRecuperarContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, paneLoginLayout.createSequentialGroup()
                        .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña)
                            .addComponent(lblEmail))
                        .addGap(217, 217, 217))
                    .addComponent(lblIntentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addComponent(lblIconContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorContraseña)
                            .addComponent(pwdContraseña)))
                    .addGroup(paneLoginLayout.createSequentialGroup()
                        .addComponent(lblIconEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorCorreo)
                            .addComponent(txtEmail))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        paneLoginLayout.setVerticalGroup(
            paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIconEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorCorreo)
                .addGap(18, 18, 18)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRecuperarContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblIntentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(paneLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 460, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        ocultarErrorMessages();
        boolean correoValidado = validarCorreo();
        boolean contraseñaValidada = validarContraseña();
        
        if(correoValidado && contraseñaValidada){
            boolean correoEncontrado = false, contraseñaEncontrada = false;
            ocultarErrorMessages();
            for(Docente doc : docentes){
                if(doc.getCorreo().equals(this.txtEmail.getText())){
                    correoEncontrado = true;
                    if(doc.getContraseña().equals(String.valueOf(this.pwdContraseña.getPassword()))){
                        contraseñaEncontrada = true;
                        
                        docenteLogged = doc;
                    }else {
                        errorContraseña = "Contraseña incorrecta.";
                        this.lblErrorContraseña.setText(errorContraseña);
                        this.lblErrorContraseña.setVisible(true);
                            
                        if(!doc.getCorreo().equals(intentoCorreo)){
                            intentoCorreo = doc.getCorreo();
                            contadorIntentos = 1;
                        } else {
                            contadorIntentos++;
                        }
                        
                        this.lblIntentos.setText("Intentos restantes: " + (3-contadorIntentos));
                        if(!this.lblIntentos.isVisible()){
                            this.lblIntentos.setVisible(true);
                        }
                    }
                    
                    break;
                }
            }
            
            if(!correoEncontrado){
                errorCorreo = "Usuario no encontrado";
                this.lblErrorCorreo.setText(errorCorreo);
                this.lblErrorCorreo.setVisible(true);
            }else if(contraseñaEncontrada){
                this.dispose();
                Prototipo.mostrarVentanaGenerador();
            }else if(contadorIntentos >= 3){
                
                JDPreguntaSeguridad frmPreguntaSeguridad = new JDPreguntaSeguridad(null, true);
                frmPreguntaSeguridad.setEnunciadoPregunta(intentoCorreo);
                frmPreguntaSeguridad.setLocationRelativeTo(this);
                ocultarErrorMessages();
                limpiarDatos();
                frmPreguntaSeguridad.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void pwdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseñaActionPerformed
        
    }//GEN-LAST:event_pwdContraseñaActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(this.txtEmail.getText().equals("example@unprg.edu.pe")){
            this.txtEmail.setText("");
            this.txtEmail.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void pwdContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaFocusGained
        if(String.valueOf(this.pwdContraseña.getPassword()).equals("12345678")){
            this.pwdContraseña.setText("");
            this.pwdContraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwdContraseñaFocusGained

    private void txtEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMousePressed

    }//GEN-LAST:event_txtEmailMousePressed

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
     
    }//GEN-LAST:event_txtEmailFocusLost

    private void pwdContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaFocusLost

    }//GEN-LAST:event_pwdContraseñaFocusLost

    private void lblIconCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMousePressed
        
    }//GEN-LAST:event_lblIconCloseMousePressed

    private void lblIconCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIconCloseMouseReleased

    private void paneHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_paneHeaderMousePressed

    private void paneHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_paneHeaderMouseDragged

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Point posicion = this.getLocation();
        Prototipo.posicionInicialX = posicion.x;
        Prototipo.posicionInicialY = posicion.y;
        this.dispose();
        Prototipo.Register();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frmLogin = null;
    }//GEN-LAST:event_formWindowClosed

    private void lblIconCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblIconCloseMouseClicked

    private void lblRecuperarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecuperarContraseñaMouseClicked
        JDOlvidoContraseña frmOlvidoContraseña = new JDOlvidoContraseña(null, true);
        frmOlvidoContraseña.setLocationRelativeTo(this);
        ocultarErrorMessages();
        frmOlvidoContraseña.setVisible(true);
    }//GEN-LAST:event_lblRecuperarContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorContraseña;
    private javax.swing.JLabel lblErrorCorreo;
    private javax.swing.JLabel lblIconClose;
    private javax.swing.JLabel lblIconContraseña;
    private javax.swing.JLabel lblIconEmail;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblRecuperarContraseña;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneLogin;
    private javax.swing.JPasswordField pwdContraseña;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

    private void ocultarErrorMessages() {
        errorCorreo = "";
        this.lblErrorCorreo.setText(errorCorreo);
        this.lblErrorCorreo.setVisible(false);
        
        errorContraseña= "";
        this.lblErrorContraseña.setText("errorContraseña");
        this.lblErrorContraseña.setVisible(false);
        
        this.lblIntentos.setVisible(false);
    }

    private boolean validarCorreo() {
        boolean banCorreo = true;
        
        if(this.txtEmail.getText().isBlank() || this.txtEmail.getText().isEmpty() || this.txtEmail.getForeground() == Color.LIGHT_GRAY){
            errorCorreo ="Se requiere un correo para continuar.\n";
            this.lblErrorCorreo.setText(errorCorreo);
            this.lblErrorCorreo.setVisible(true);
            banCorreo = false;
        }
        
        if(!this.txtEmail.getText().matches("^[a-z._]+@unprg\\.edu\\.pe$")){
            errorCorreo += "Ingrese un correo válido";
            this.lblErrorCorreo.setText(errorCorreo);
            this.lblErrorCorreo.setVisible(true);
            banCorreo = false;
        }

        return banCorreo;
    }
    
    private boolean validarContraseña() {
        boolean banContraseña = true;
        
        if(String.valueOf(this.pwdContraseña.getPassword()).isBlank() || this.txtEmail.getText().isEmpty() || this.pwdContraseña.getForeground() == Color.LIGHT_GRAY){
            errorContraseña ="Se requiere una contraseña para continuar.\n";
            this.lblErrorContraseña.setText(errorContraseña);
            this.lblErrorContraseña.setVisible(true);
            banContraseña = false;
        }
        return banContraseña;
    }

    private void limpiarDatos() {
        this.txtEmail.setText("");
        this.pwdContraseña.setText("");
    }
}
