/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gestion;

import Clases.Docente;
import Clases.Facultades;
import Clases.Escuela;
import alerts.MostrarMensaje;
import enums.EnumPaths;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.awt.Point;
import java.io.IOException;
import static Data.Data.*;
import javax.swing.DefaultComboBoxModel;
import prototipo.Prototipo;

/**
 *
 * @author USUARIO
 */
public class JFRegister extends javax.swing.JFrame {
    int xMouse, yMouse;
    private static JFRegister frmRegister = null;
    private static String errorNombre = "", errorApellidos = "",
            errorGenero = "", errorFacultad = "", errorEscuela = "",
            errorGrado = "", errorTitulo = "", errorCorreo = "",
            errorContraseña = "", errorConfirmContraseña = "";
    
    public static JFrame crear() {
        if(frmRegister == null){
            frmRegister = new JFRegister();
        }
        
        return frmRegister;        
    }

    /**
     * Creates new form JFRegister
     */
    public JFRegister() {
        initComponents();
        
        this.paneRegister.requestFocusInWindow();
        setIconImage(new ImageIcon(getClass().getResource(EnumPaths.ICON.getRuta())).getImage());
        
        iniciarCMBs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneImageLateralRegister = new javax.swing.JPanel();
        lblImageLateralRegister = new javax.swing.JLabel();
        paneHeader = new javax.swing.JPanel();
        lblIconClose = new javax.swing.JLabel();
        scrollPaneRegister = new javax.swing.JScrollPane();
        paneRegister = new javax.swing.JPanel();
        lblIconImagotipo = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmContraseña = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        pwdContraseña = new javax.swing.JPasswordField();
        pwdConfirmContraseña = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblIconContraseña = new javax.swing.JLabel();
        lblIconConfirContraseña = new javax.swing.JLabel();
        lblIconEmail = new javax.swing.JLabel();
        lblIconNombres = new javax.swing.JLabel();
        lblIconApellidos = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        lblIconGenero = new javax.swing.JLabel();
        lblPregunta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblIconPreguntaRegister = new javax.swing.JLabel();
        cmbPregunta = new javax.swing.JComboBox<>();
        lblRespuesta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        lblFacultad = new javax.swing.JLabel();
        lblIconFacultad = new javax.swing.JLabel();
        cmbFacultad = new javax.swing.JComboBox<>();
        lblEscuela = new javax.swing.JLabel();
        lblIconEscuela = new javax.swing.JLabel();
        cmbEscuela = new javax.swing.JComboBox<>();
        lblGrado = new javax.swing.JLabel();
        lblIconGrado = new javax.swing.JLabel();
        cmbGrado = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImageLateralRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PlazaDelSaber_UNRPG.png"))); // NOI18N
        lblImageLateralRegister.setFocusable(false);

        javax.swing.GroupLayout paneImageLateralRegisterLayout = new javax.swing.GroupLayout(paneImageLateralRegister);
        paneImageLateralRegister.setLayout(paneImageLateralRegisterLayout);
        paneImageLateralRegisterLayout.setHorizontalGroup(
            paneImageLateralRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(paneImageLateralRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneImageLateralRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblImageLateralRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        paneImageLateralRegisterLayout.setVerticalGroup(
            paneImageLateralRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(paneImageLateralRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paneImageLateralRegisterLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblImageLateralRegister)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(paneImageLateralRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        paneHeader.setBackground(new java.awt.Color(255, 255, 255));
        paneHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneHeaderMouseDragged(evt);
            }
        });
        paneHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneHeaderMousePressed(evt);
            }
        });

        lblIconClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Close.png"))); // NOI18N
        lblIconClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIconClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIconCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneHeaderLayout = new javax.swing.GroupLayout(paneHeader);
        paneHeader.setLayout(paneHeaderLayout);
        paneHeaderLayout.setHorizontalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addGap(0, 828, Short.MAX_VALUE)
                .addComponent(lblIconClose))
        );
        paneHeaderLayout.setVerticalGroup(
            paneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneHeaderLayout.createSequentialGroup()
                .addComponent(lblIconClose)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(paneHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 30));

        scrollPaneRegister.setBorder(null);
        scrollPaneRegister.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneRegister.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPaneRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        paneRegister.setBackground(new java.awt.Color(255, 255, 255));
        paneRegister.setMaximumSize(new java.awt.Dimension(32767, 500));

        lblIconImagotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagotipo.png"))); // NOI18N

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombres.setText("Nombres:");

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellidos.setText("Apellidos:");

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreo.setText("Correo institucional:");

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");

        lblConfirmContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConfirmContraseña.setText("Confirmar contraseña:");

        txtNombres.setForeground(Color.LIGHT_GRAY);
        txtNombres.setText("Ingrese su nombre");
        txtNombres.setToolTipText("Ingrese su nombre");
        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        txtApellidos.setForeground(Color.LIGHT_GRAY);
        txtApellidos.setText("Ingrese sus apellidos");
        txtApellidos.setToolTipText("Ingrese sus apellidos");
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });

        txtCorreo.setForeground(Color.LIGHT_GRAY);
        txtCorreo.setText("example@unprg.edu.pe");
        txtCorreo.setToolTipText("Digite su correo institucional");
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        pwdContraseña.setForeground(Color.LIGHT_GRAY);
        pwdContraseña.setText("12345678");
        pwdContraseña.setToolTipText("Digite su contraseña");
        pwdContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pwdContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdContraseñaFocusLost(evt);
            }
        });

        pwdConfirmContraseña.setForeground(Color.LIGHT_GRAY);
        pwdConfirmContraseña.setText("12345678");
        pwdConfirmContraseña.setToolTipText("Digite nuevamente su contraseña");
        pwdConfirmContraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        pwdConfirmContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdConfirmContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdConfirmContraseñaFocusLost(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 102, 204));
        lblLogin.setText("Tengo una cuenta");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });

        lblIconContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Contraseña.png"))); // NOI18N

        lblIconConfirContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Contraseña.png"))); // NOI18N

        lblIconEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Email.png"))); // NOI18N

        lblIconNombres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_User.png"))); // NOI18N

        lblIconApellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_User.png"))); // NOI18N

        lblGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGenero.setText("Género:");

        cmbGenero.setToolTipText("Seleccione su género");
        cmbGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        lblIconGenero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Genero.png"))); // NOI18N

        lblPregunta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPregunta.setText("Pregunta de seguridad:");

        lblIconPreguntaRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Pregunta_Register.png"))); // NOI18N

        cmbPregunta.setToolTipText("En caso de olvidar su contraseña, le haremos esta pregunta para verificar su identidad.");
        cmbPregunta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        cmbPregunta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPreguntaItemStateChanged(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRespuesta.setText("Respuesta:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Pregunta_Register.png"))); // NOI18N

        txtRespuesta.setToolTipText("Responda cuidadosamente. Esta información se usará para recuperar su cuenta si lo necesita.");
        txtRespuesta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        lblFacultad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFacultad.setText("Facultad:");

        lblIconFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Facultad.png"))); // NOI18N

        cmbFacultad.setToolTipText("Seleccione su facultad");
        cmbFacultad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));
        cmbFacultad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFacultadItemStateChanged(evt);
            }
        });

        lblEscuela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEscuela.setText("Escuela profesional:");

        lblIconEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Facultad.png"))); // NOI18N

        cmbEscuela.setToolTipText("Seleccione su escuela");
        cmbEscuela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        lblGrado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGrado.setText("Grado académico:");

        lblIconGrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Icons/Icon_Grado.png"))); // NOI18N

        cmbGrado.setToolTipText("Seleccione su grado académico");
        cmbGrado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 204)));

        javax.swing.GroupLayout paneRegisterLayout = new javax.swing.GroupLayout(paneRegister);
        paneRegister.setLayout(paneRegisterLayout);
        paneRegisterLayout.setHorizontalGroup(
            paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRegisterLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegisterLayout.createSequentialGroup()
                        .addComponent(lblIconImagotipo)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegisterLayout.createSequentialGroup()
                        .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblRespuesta)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblConfirmContraseña)
                                    .addComponent(lblPregunta)
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblLogin))
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2)
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconConfirContraseña)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pwdConfirmContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconContraseña)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(pwdContraseña))
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(paneRegisterLayout.createSequentialGroup()
                                    .addComponent(lblIconPreguntaRegister)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblApellidos)
                                .addComponent(lblNombres)
                                .addComponent(lblGenero)
                                .addGroup(paneRegisterLayout.createSequentialGroup()
                                    .addComponent(lblIconApellidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtApellidos))
                                .addGroup(paneRegisterLayout.createSequentialGroup()
                                    .addComponent(lblIconNombres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(paneRegisterLayout.createSequentialGroup()
                                    .addComponent(lblIconGenero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jSeparator1)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegisterLayout.createSequentialGroup()
                        .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(paneRegisterLayout.createSequentialGroup()
                                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGrado)
                                    .addComponent(lblEscuela)
                                    .addComponent(lblFacultad)
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconFacultad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconEscuela)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbEscuela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(paneRegisterLayout.createSequentialGroup()
                                        .addComponent(lblIconGrado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbGrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        paneRegisterLayout.setVerticalGroup(
            paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneRegisterLayout.createSequentialGroup()
                .addComponent(lblIconImagotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIconGenero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFacultad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEscuela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIconConfirContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdConfirmContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneRegisterLayout.createSequentialGroup()
                        .addComponent(cmbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paneRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin)))
                    .addComponent(lblIconPreguntaRegister))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        scrollPaneRegister.setViewportView(paneRegister);

        getContentPane().add(scrollPaneRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 460, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblIconCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIconCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblIconCloseMouseClicked

    private void paneHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_paneHeaderMousePressed

    private void paneHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_paneHeaderMouseDragged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        frmRegister = null;
    }//GEN-LAST:event_formWindowClosed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        Point posicion = this.getLocation();
        Prototipo.posicionInicialX = posicion.x;
        Prototipo.posicionInicialY = posicion.y;
        this.dispose();
        Prototipo.login();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        boolean banCorreo = false;
        
        if(ValidarDatos()){
            for(Docente doc : docentes){
                if(doc.getCorreo().equals(this.txtCorreo.getText())){
                    MostrarMensaje.error("Correo ya registrado.");
                    banCorreo = true;
                }
            }
            
            if(!banCorreo){
                //Docente
                //String nombres
                //String apellidos
                //String genero
                //Integer facultad
                //Integer escuela
                //String gradoAcademico
                //String correo
                //String contraseña
                //int preguntaSeguridad
                //String respuestaSeguridad
                Docente doc = new Docente(
                                this.txtNombres.getText(),
                                this.txtApellidos.getText(),
                                (String) this.cmbGenero.getSelectedItem(),
                                this.cmbFacultad.getSelectedIndex(),
                                this.cmbEscuela.getSelectedIndex(),
                                (String) this.cmbGrado.getSelectedItem(),
                                this.txtCorreo.getText(),
                                String.valueOf(this.pwdContraseña.getPassword()),
                                this.cmbPregunta.getSelectedIndex(),
                                this.txtRespuesta.getText()
                        );
                        
                docentes.add(doc);
                actualizarDataDocentes(doc);

                MostrarMensaje.confirm("Usuario registrado");
                this.dispose();
                Prototipo.login();
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void pwdConfirmContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmContraseñaFocusLost

    }//GEN-LAST:event_pwdConfirmContraseñaFocusLost

    private void pwdConfirmContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdConfirmContraseñaFocusGained
        if(String.valueOf(this.pwdConfirmContraseña.getPassword()).equals("12345678")){
            this.pwdConfirmContraseña.setForeground(Color.black);
            this.pwdConfirmContraseña.setText("");
        }
    }//GEN-LAST:event_pwdConfirmContraseñaFocusGained

    private void pwdContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaFocusLost

    }//GEN-LAST:event_pwdContraseñaFocusLost

    private void pwdContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdContraseñaFocusGained
        if(String.valueOf(this.pwdContraseña.getPassword()).equals("12345678")){
            this.pwdContraseña.setForeground(Color.black);
            this.pwdContraseña.setText("");
        }
    }//GEN-LAST:event_pwdContraseñaFocusGained

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost

    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusGained
        if(this.txtCorreo.getText().equals("example@unprg.edu.pe")){
            this.txtCorreo.setForeground(Color.black);
            this.txtCorreo.setText("");
        }
    }//GEN-LAST:event_txtCorreoFocusGained

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost

    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusGained
        if(this.txtApellidos.getText().equals("Ingrese sus apellidos")){
            this.txtApellidos.setForeground(Color.black);
            this.txtApellidos.setText("");
        }
    }//GEN-LAST:event_txtApellidosFocusGained

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost

    }//GEN-LAST:event_txtNombresFocusLost

    private void txtNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusGained
        if(this.txtNombres.getText().equals("Ingrese su nombre")){
            this.txtNombres.setForeground(Color.black);
            this.txtNombres.setText("");
        }
    }//GEN-LAST:event_txtNombresFocusGained

    private void cmbPreguntaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPreguntaItemStateChanged
        if(this.cmbPregunta.getSelectedIndex() == -1){
            this.txtRespuesta.setEnabled(false);
        }else{
            this.txtRespuesta.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmbPreguntaItemStateChanged

    private void cmbFacultadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFacultadItemStateChanged
        if(this.cmbFacultad.getSelectedIndex() == -1){
            if(this.cmbEscuela.isEnabled()){
                this.cmbEscuela.setEnabled(false);
                this.cmbEscuela.setSelectedIndex(-1);
            }
        }else {
            this.cmbEscuela.removeAllItems();
            
            Escuela esc = new Escuela();
            this.cmbEscuela.setModel(new DefaultComboBoxModel<>(esc.getEscuelas(this.cmbFacultad.getSelectedIndex())));
            this.cmbEscuela.setSelectedIndex(-1);

            this.cmbEscuela.setEnabled(true);
            this.cmbEscuela.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_cmbFacultadItemStateChanged

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbEscuela;
    private javax.swing.JComboBox<String> cmbFacultad;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbGrado;
    private javax.swing.JComboBox<String> cmbPregunta;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblConfirmContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblIconApellidos;
    private javax.swing.JLabel lblIconClose;
    private javax.swing.JLabel lblIconConfirContraseña;
    private javax.swing.JLabel lblIconContraseña;
    private javax.swing.JLabel lblIconEmail;
    private javax.swing.JLabel lblIconEscuela;
    private javax.swing.JLabel lblIconFacultad;
    private javax.swing.JLabel lblIconGenero;
    private javax.swing.JLabel lblIconGrado;
    private javax.swing.JLabel lblIconImagotipo;
    private javax.swing.JLabel lblIconNombres;
    private javax.swing.JLabel lblIconPreguntaRegister;
    private javax.swing.JLabel lblImageLateralRegister;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JPanel paneHeader;
    private javax.swing.JPanel paneImageLateralRegister;
    private javax.swing.JPanel paneRegister;
    private javax.swing.JPasswordField pwdConfirmContraseña;
    private javax.swing.JPasswordField pwdContraseña;
    private javax.swing.JScrollPane scrollPaneRegister;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtRespuesta;
    // End of variables declaration//GEN-END:variables

    private boolean ValidarDatos() {
        String errorMessage = "";
        
        if(this.txtNombres.getText().isBlank() || this.txtNombres.getText().isEmpty() || this.txtNombres.getText().equals("Ingrese su nombre")){
            errorMessage += "\n- Nombres.";
        }
        
        if(this.txtApellidos.getText().isBlank() || this.txtApellidos.getText().isEmpty() || this.txtApellidos.getText().equals("Ingrese sus apellidos")){
            errorMessage += "\n- Apellidos.";
        }
        
        if(this.cmbGenero.getSelectedIndex()==-1){
            errorMessage += "\n- Género.";
        }
        
        if(this.cmbFacultad.getSelectedIndex()==-1){
            errorMessage += "\n- Facultad.";
        }
        
        if(this.cmbEscuela.getSelectedIndex()==-1){
            errorMessage += "\n- Escuela.";
        }
        
        if(this.cmbGrado.getSelectedIndex()==-1){
            errorMessage += "\n- Grado académico.";
        }
        if(this.txtCorreo.getText().isBlank() || this.txtCorreo.getText().isEmpty() || this.txtCorreo.getText().equals("example@unprg.edu.pe")){
            errorMessage += "\n- Correo.";
        }
                
        if(String.valueOf(this.pwdContraseña.getPassword()).isBlank() || String.valueOf(this.pwdContraseña.getPassword()).isEmpty() || this.pwdContraseña.getForeground() == Color.LIGHT_GRAY){
            errorMessage += "\n- Contraseña.";
        }
        
        if(String.valueOf(this.pwdConfirmContraseña.getPassword()).isBlank() || String.valueOf(this.pwdConfirmContraseña.getPassword()).isEmpty() || this.pwdConfirmContraseña.getForeground() == Color.LIGHT_GRAY){
            errorMessage += "\n- Confirmación de contraseña.";
        }
        
        if(!errorMessage.isEmpty()){
            MostrarMensaje.error("Datos no registrados: " + errorMessage);
            return false;
        }
                
        String regexContraseña = "^(?=.*[A-Za-z])(?=.*\\d).{8,}$";
            
        if (!String.valueOf(this.pwdContraseña.getPassword()).matches(regexContraseña)) {
            errorMessage += "Se necesita una contraseña válida.\n- 8 caracteres como mínimo.\n- Al menos un número.\n- Al menos una letra.";
            MostrarMensaje.error(errorMessage);
            return false;
        }
        
        if(!String.valueOf(this.pwdContraseña.getPassword()).equals(String.valueOf(this.pwdConfirmContraseña.getPassword()))){
            errorMessage += "Las contraseñas no coinciden.";
            MostrarMensaje.error(errorMessage);
            return false;
        }
        
        String regexCorreo = "^[a-z._]+@unprg\\.edu\\.pe$";
        if(!this.txtCorreo.getText().matches(regexCorreo)){
            errorMessage += "Ingrese un correo válido";
            MostrarMensaje.error(errorMessage);
            return false;
        }
        if(this.cmbPregunta.getSelectedIndex() == -1){
            errorMessage += "Seleccione pregunta de seguridad en caso de olvidar su contraseña.";
            MostrarMensaje.error(errorMessage);
            return false;
        }
        
        if(this.txtRespuesta.getText().isBlank() || this.txtRespuesta.getText().isEmpty()){
            errorMessage += "Ingrese una respuesta a la pregunta de seguridad.";
            MostrarMensaje.error(errorMessage);
            return false;
        }
        
        return true;
    }

    private void iniciarCMBs() {
        Facultades fac = new Facultades();
        this.cmbFacultad.setModel(new DefaultComboBoxModel<>(fac.getFacultades()));
        this.cmbFacultad.setSelectedIndex(-1);
        
        this.cmbPregunta.setModel(new DefaultComboBoxModel<>(PREGUNTAS_SEGURIDAD));
        this.cmbPregunta.setSelectedIndex(-1);
        
        String[] opGenero = {"Masculino", "Femenino"};
        this.cmbGenero.setModel(new DefaultComboBoxModel<>(opGenero));
        this.cmbGenero.setSelectedIndex(-1);
        
        String[] opGrado = {"Bachiller", "Licenciado", "Magister", "Doctor"};
        this.cmbGrado.setModel(new DefaultComboBoxModel<>(opGrado));
        this.cmbGrado.setSelectedIndex(-1);
        
        this.cmbEscuela.setEnabled(false);
        this.txtRespuesta.setEnabled(false);
    }
}
